../bin/raytrace 01_sphere.json
../bin/raytrace 02_quad.json
../bin/raytrace 03_plane.json
../bin/raytrace 04_balls.json
../bin/raytrace 05_refl.json
../bin/raytrace 06_aa.json
../bin/raytrace 07_plane.json
../bin/raytrace 08_refr.json
../bin/raytrace 09_cylinder.json
../bin/raytrace 09_cylinder_rotate.json
../bin/raytrace 10_refr.json
